name: shelfie
services:
  frontend:
    build:
      context: ./src/frontend/
    ports:
        - "${PORT:-8081}:8081"
    environment:
      - PORT=8081

  shelfie-sam1-img:
    build:
      context: ./src/backend/
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    env_file:
      - ./src/backend/.env
